### ISSUE TITLE
Outside testing prior to release?

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/TF-RED-Utils#2]
If so what happened and how does it work?

**Comment by Jmaster9999** [comment]
Uhhh... It works in MP. Not exactly sure what you are trying to ask.

**Comment by coachwn** [comment]
I am asking exactly what the title says...did anyone other than you test it before you publisted it? There have been way too many times things haven't worked as advertised or only partially worked when released and also how does it work? What do the people who use it have to do or what do they expect it to do when used?

**Comment by Jmaster9999** [comment]
KISS is in effect with this system. The addon works as advertised. It has been THOROUGHLY tested by myself, but if that isn't good enough Iowa is using it in his mission and it works. If it says it has been tested then it has been tested... 

In the Readme is states that adding item amounts via textfield are under 'Planned features', and are not implemented. The documentation for using the system is ingame and is part of the modules themselves, with the module descriptions giving their usage instructions. Any other documentation would exist as a wiki entry on the repo.
